apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ronin.fullname" . }}-data
spec:
  accessModes:
{{- range .Values.storage.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
