import { del, get, post, put } from './api.js';
import { json, page } from './dom.js';
let dirty = false;
let activeJobId = '';
const ctx = () => { const f = new FormData(document.querySelector('#notebook-context')); return { w: encodeURIComponent(f.get('workspace')), p: encodeURIComponent(f.get('project')) }; };
const base = () => { const c = ctx(); return `/v1/workspaces/${c.w}/projects/${c.p}/notebooks`; };
export async function notebookStudio() {
  document.querySelector('#view').innerHTML = `${page('Notebook Studio', 'DATA ENGINEERING')}<section class="panel"><form id="notebook-context" class="toolbar"><label>Workspace<input class="field" name="workspace" value="default" required></label><label>Project<input class="field" name="project" value="examples/demo" required></label><button class="button" type="submit">Refresh</button></form><div id="notebook-list" class="loading">Loading notebooks…</div></section><section class="panel"><h2>Notebook editor</h2><form id="notebook-editor"><label>Notebook ID<input class="field" name="id" required></label><label>Revision<input class="field" name="revision" type="number" min="1" required></label><label>Runtime<select class="field" name="runtime"><option>local</option><option>container</option></select></label><label>Document JSON<textarea class="field sql-editor" name="document" rows="12" required>{"schema":"ronin.notebook/v1","cells":[]}</textarea><div class="toolbar"><button class="button primary" data-notebook-action="save">Save</button><button class="button" data-notebook-action="create">Create</button><button class="button" data-notebook-action="archive">Archive</button><button class="button danger" data-notebook-action="delete">Delete</button><button class="button primary" data-notebook-action="run-all" type="button">Run all cells</button><button class="button" data-notebook-action="run-cell" type="button">Run first cell</button></div></form><pre id="notebook-result" class="code">Select a notebook.</pre><div id="notebook-run" class="panel">No execution requested.</div></section>`;
  document.querySelector('#notebook-editor').querySelector('[data-notebook-action="run-cell"]').insertAdjacentHTML('afterend', '<button class="button danger" data-notebook-action="cancel" type="button">Cancel run</button>');
  document.querySelector('#notebook-editor').addEventListener('input', () => { dirty = true; });
  document.querySelector('#notebook-context').addEventListener('submit', async event => { event.preventDefault(); await load(); });
  document.querySelector('#notebook-editor').addEventListener('submit', handleSubmit);
  await load();
}
async function load() { const out = document.querySelector('#notebook-list'); try { const data = await get(base()); out.innerHTML = (data.items || []).map(x => `<button type="button" class="button" data-notebook-id="${x.id}">${x.id} (r${x.revision})</button>`).join(' ') || '<div class="empty">No notebooks.</div>'; out.querySelectorAll('[data-notebook-id]').forEach(button => button.addEventListener('click', () => openNotebook(button.dataset.notebookId))); } catch (e) { out.textContent = `Notebook listing failed: ${e.message}`; } }
async function openNotebook(notebookId) { if (dirty && !window.confirm('Discard unsaved changes?')) return; try { const x = await get(`${base()}/${encodeURIComponent(notebookId)}`), f = document.querySelector('#notebook-editor'); f.querySelector('[name="id"]').value = x.id; f.querySelector('[name="revision"]').value = x.revision; f.querySelector('[name="runtime"]').value = x.runtime || 'local'; f.querySelector('[name="document"]').value = JSON.stringify(x.document, null, 2); dirty = false; document.querySelector('#notebook-result').textContent = json(x); } catch (err) { document.querySelector('#notebook-result').textContent = `Notebook load failed: ${err.message}`; } }
async function handleSubmit(e) { e.preventDefault(); const f = new FormData(e.target), action = e.submitter?.dataset.notebookAction || 'save', id = encodeURIComponent(f.get('id')), body = { expected_revision: Number(f.get('revision')), document: JSON.parse(f.get('document')) }; try { let result; if (action === 'create') result = await post(base(), { id: f.get('id'), document: body.document }); else if (action === 'delete') result = await del(`${base()}/${id}`, { headers: { 'If-Match': String(body.expected_revision) } }); else if (action === 'archive') result = await post(`${base()}/${id}/archive`, { expected_revision: body.expected_revision }); else result = await put(`${base()}/${id}`, body); document.querySelector('#notebook-result').textContent = json(result); dirty = false; await load(); } catch (err) { document.querySelector('#notebook-result').textContent = `Notebook operation failed: ${err.message}`; } }
document.addEventListener('click', async e => { const cancel = e.target.closest('[data-notebook-action="cancel"]'); if (cancel) { if (!activeJobId) { document.querySelector('#notebook-run').textContent = 'No active notebook job.'; return; } try { const result = await post(`/v1/jobs/${encodeURIComponent(activeJobId)}/cancel`, {}); document.querySelector('#notebook-run').textContent = json(result); } catch (err) { document.querySelector('#notebook-run').textContent = `Notebook cancellation failed: ${err.message}`; } return; } const run = e.target.closest('[data-notebook-action="run-all"], [data-notebook-action="run-cell"]'); if (!run) return; try { const f = new FormData(document.querySelector('#notebook-editor')), doc = JSON.parse(f.get('document')), mode = run.dataset.notebookAction === 'run-cell' ? 'cell' : 'all', cell_id = mode === 'cell' ? doc.cells?.[0]?.id : undefined; if (mode === 'cell' && !cell_id) throw new Error('Notebook has no selectable cells'); const project = document.querySelector('#notebook-context [name="project"]').value.trim(), notebook = String(f.get('id')), result = await post('/v1/jobs', { project, target: `notebook:${notebook}`, parameters: { document: doc, mode, cell_id, runtime: f.get('runtime') } }, { headers: { 'Idempotency-Key': `studio-notebook-${project}-${notebook}-${mode}` } }); activeJobId = result.id || ''; document.querySelector('#notebook-run').textContent = json(result); if (result.id) monitor(result.id); } catch (err) { document.querySelector('#notebook-run').textContent = `Notebook execution failed: ${err.message}`; } });
async function monitor(id) { for (let i = 0; i < 60; i += 1) { try { const [job, results] = await Promise.all([get(`/v1/jobs/${encodeURIComponent(id)}`), get(`/v1/jobs/${encodeURIComponent(id)}/results`)]); document.querySelector('#notebook-run').textContent = json({ job, results }); if (['succeeded', 'failed', 'cancelled'].includes(job.state)) return; } catch (e) { return; } await new Promise(r => setTimeout(r, 1000)); } }
window.addEventListener('beforeunload', e => { if (dirty) { e.preventDefault(); e.returnValue = ''; } });
window.addEventListener('hashchange', () => { if (location.hash.slice(1) === 'notebooks') notebookStudio(); });
if (location.hash.slice(1) === 'notebooks') setTimeout(notebookStudio, 0);
setInterval(() => { if (location.hash.slice(1) === 'notebooks' && !document.querySelector('#notebook-editor')) notebookStudio(); }, 100);
