import { get, post, put } from './api.js';
import { json, page } from './dom.js';

function render() {
  if (location.hash.slice(1) !== 'semantic') return;
  const view = document.querySelector('#view'); if (!view) return;
  view.innerHTML = `${page('Semantic Studio', 'METRICS · DASHBOARDS')}<section class="panel"><form id="semantic-model-form" class="toolbar"><input class="field" name="workspace" value="default" required><input class="field" name="project" value="examples/demo" required><button class="button" type="submit">List models</button></form><pre id="semantic-model-result" class="code">No models loaded.</pre></section><section class="panel"><form id="semantic-dashboard-form" class="toolbar"><input class="field" name="workspace" value="default" required><input class="field" name="project" value="examples/demo" required><input class="field" name="dashboard" value="sales_dashboard" required><button class="button" type="submit" name="action" value="list">List dashboards</button><button class="button primary" type="submit" name="action" value="execute">Execute dashboard</button><button class="button" type="submit" name="action" value="save">Save dashboard</button><textarea class="field" name="definition" rows="2">{"id":"sales_dashboard","title":"Sales"}</textarea></form><pre id="semantic-dashboard-result" class="code">No dashboards loaded.</pre></section><section class="panel"><form id="semantic-query-form"><input class="field" name="workspace" value="default" required><input class="field" name="project" value="examples/demo" required><label>Metric query JSON<textarea class="field sql-editor" name="query" rows="5">{"model_id":"sales","measures":["revenue"],"dimensions":[],"filters":[],"limit":100}</textarea></label><button class="button primary" type="submit">Run metric query</button></form><pre id="semantic-query-result" class="code">No query executed.</pre></section><section class="panel"><form id="semantic-join-form"><input class="field" name="workspace" value="default" required><input class="field" name="project" value="examples/demo" required><label>Join JSON<textarea class="field" name="join" rows="5">{"left_model":"sales","right_model":"customers","on":[["customer_id","id"]],"limit":100}</textarea></label><button class="button" type="submit">Run join</button></form><pre id="semantic-join-result" class="code">No join executed.</pre></section>`;
}

document.addEventListener('submit', async event => {
  const form = event.target; if (!(form instanceof HTMLFormElement)) return;
  const data = new FormData(form); const workspace = encodeURIComponent(String(data.get('workspace'))); const project = encodeURIComponent(String(data.get('project'))); const path = `/v1/workspaces/${workspace}/projects/${project}/semantic/`;
  try {
    if (form.id === 'semantic-model-form') { event.preventDefault(); document.querySelector('#semantic-model-result').textContent = json(await get(`${path}models`)); }
    else if (form.id === 'semantic-dashboard-form') { event.preventDefault(); const action = String(data.get('action')); const dashboard = encodeURIComponent(String(data.get('dashboard'))); const result = action === 'execute' ? await post(`${path}dashboards/${dashboard}/execute`, {}) : action === 'save' ? await put(`${path}dashboards/${dashboard}`, JSON.parse(String(data.get('definition')))) : await get(`${path}dashboards`); document.querySelector('#semantic-dashboard-result').textContent = json(result); }
    else if (form.id === 'semantic-query-form') { event.preventDefault(); document.querySelector('#semantic-query-result').textContent = json(await post(`${path}query`, JSON.parse(String(data.get('query'))))); }
    else if (form.id === 'semantic-join-form') { event.preventDefault(); document.querySelector('#semantic-join-result').textContent = json(await post(`${path}join`, JSON.parse(String(data.get('join'))))); }
  } catch (error) { const target = form.id === 'semantic-model-form' ? '#semantic-model-result' : form.id === 'semantic-dashboard-form' ? '#semantic-dashboard-result' : form.id === 'semantic-join-form' ? '#semantic-join-result' : '#semantic-query-result'; document.querySelector(target).textContent = `Semantic operation failed: ${error.message}`; }
});
setTimeout(() => { window.addEventListener('hashchange', render); if (location.hash.slice(1) === 'semantic') render(); }, 0);
