"""Pure, provider-neutral domain primitives for Ronin."""

from .diagnostics import (
    DiagnosticCatalog,
    DiagnosticFact,
    DiagnosticFinding,
    DiagnosticPredicate,
    DiagnosticRule,
    builtin_diagnostic_catalog,
)
from .ids import InstanceAnchor, NodeId, allocate_instance_keys
from .ir import (
    Edge,
    FrozenList,
    FrozenMap,
    Node,
    OperatorRef,
    Origin,
    Pipeline,
    PipelineConfig,
    Port,
    SchemaRef,
    freeze_value,
    thaw_value,
)
from .operators import (
    OperatorCatalog,
    OperatorContract,
    OperatorParameter,
    OperatorPort,
    OperatorViolation,
    builtin_operator_catalog,
    operator_parameter_value,
    validate_operator_node,
)
from .project_manifest import PROJECT_MANIFEST_PATH, PROJECT_MANIFEST_SCHEMA, ProjectManifest
from .projects import (
    CapabilityRequirement,
    ExecutionProfile,
    Project,
    ProjectCollection,
    ProjectId,
    RepositoryBinding,
    RepositorySyncPolicy,
    RuntimeProfileRef,
)
from .runtime_profiles import (
    ProfileEvaluation,
    RequirementCheck,
    RuntimeCapability,
    RuntimeCatalog,
    RuntimeProfile,
    RuntimeResolution,
    resolve_runtime,
)

__all__ = (
    "CapabilityRequirement",
    "DiagnosticCatalog",
    "DiagnosticFact",
    "DiagnosticFinding",
    "DiagnosticPredicate",
    "DiagnosticRule",
    "Edge",
    "ExecutionProfile",
    "FrozenList",
    "FrozenMap",
    "InstanceAnchor",
    "Node",
    "NodeId",
    "OperatorCatalog",
    "OperatorContract",
    "OperatorParameter",
    "OperatorPort",
    "OperatorRef",
    "OperatorViolation",
    "Origin",
    "PROJECT_MANIFEST_PATH",
    "PROJECT_MANIFEST_SCHEMA",
    "Pipeline",
    "PipelineConfig",
    "Port",
    "ProfileEvaluation",
    "Project",
    "ProjectCollection",
    "ProjectId",
    "ProjectManifest",
    "RepositoryBinding",
    "RepositorySyncPolicy",
    "RequirementCheck",
    "RuntimeCapability",
    "RuntimeCatalog",
    "RuntimeProfile",
    "RuntimeProfileRef",
    "RuntimeResolution",
    "SchemaRef",
    "allocate_instance_keys",
    "builtin_diagnostic_catalog",
    "builtin_operator_catalog",
    "freeze_value",
    "operator_parameter_value",
    "resolve_runtime",
    "thaw_value",
    "validate_operator_node",
)
