"""Pure, provider-neutral domain primitives for Ronin."""

from .ids import NodeId
from .ir import (
    Edge,
    FrozenList,
    FrozenMap,
    Node,
    OperatorRef,
    Origin,
    Pipeline,
    PipelineConfig,
    Port,
    SchemaRef,
    freeze_value,
    thaw_value,
)
from .projects import (
    CapabilityRequirement,
    ExecutionProfile,
    Project,
    ProjectCollection,
    ProjectId,
    RepositoryBinding,
    RuntimeProfileRef,
)
from .runtime_profiles import (
    ProfileEvaluation,
    RequirementCheck,
    RuntimeCapability,
    RuntimeCatalog,
    RuntimeProfile,
    RuntimeResolution,
    resolve_runtime,
)

__all__ = (
    "CapabilityRequirement",
    "Edge",
    "ExecutionProfile",
    "FrozenList",
    "FrozenMap",
    "Node",
    "NodeId",
    "OperatorRef",
    "Origin",
    "Pipeline",
    "PipelineConfig",
    "Port",
    "ProfileEvaluation",
    "Project",
    "ProjectCollection",
    "ProjectId",
    "RepositoryBinding",
    "RequirementCheck",
    "RuntimeCapability",
    "RuntimeCatalog",
    "RuntimeProfile",
    "RuntimeProfileRef",
    "RuntimeResolution",
    "SchemaRef",
    "freeze_value",
    "resolve_runtime",
    "thaw_value",
)
