"""Fail-closed qualification for the frozen Ronin v0.1 acceptance journey."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from xml.etree import ElementTree

EXPECTED_STEP_NAMES: tuple[str, ...] = tuple(
    f"test_step_{index:02d}_{suffix}"
    for index, suffix in enumerate(
        (
            "compose_reaches_healthy_within_60s",
            "doctor_reports_all_checks_passing",
            "validate_accepts_demo_project",
            "plan_prints_order_and_levels",
            "submit_returns_queued_job",
            "worker_claims_and_executes_first_cells",
            "kill_worker_orphans_lease",
            "restart_waits_for_lease_expiry",
            "reclaimed_attempt_resumes_at_cell_four",
            "job_reaches_succeeded",
            "events_contiguous_across_attempts_with_terminal",
            "evidence_present_for_all_six_cells",
            "replayed_idempotency_key_returns_same_job",
            "cancel_removes_container",
            "sdk_round_trip_matches_cli",
        ),
        start=1,
    )
)


class AcceptanceGateError(ValueError):
    """Raised when v0.1 acceptance evidence is incomplete or invalid."""


@dataclass(frozen=True, slots=True)
class AcceptanceCounts:
    """Machine-readable summary of the frozen acceptance-step outcomes."""

    live: int
    passed: int
    skipped: int
    xfailed: int
    failed: int
    errors: int
    missing: int
    unexpected: int
    skipped_steps: tuple[str, ...] = ()

    @property
    def total_expected(self) -> int:
        return len(EXPECTED_STEP_NAMES)

    @property
    def is_strict_success(self) -> bool:
        return self.passed == self.total_expected and all(
            value == 0
            for value in (
                self.skipped,
                self.xfailed,
                self.failed,
                self.errors,
                self.missing,
                self.unexpected,
            )
        )

    def to_evidence(self) -> dict[str, int | bool | list[str]]:
        return {
            "live": self.live,
            "passed": self.passed,
            "skipped": self.skipped,
            "xfailed": self.xfailed,
            "failed": self.failed,
            "errors": self.errors,
            "missing": self.missing,
            "unexpected": self.unexpected,
            "total_expected": self.total_expected,
            "strict_success": self.is_strict_success,
            "skipped_steps": list(self.skipped_steps),
        }


def evaluate_junit(report_path: Path) -> AcceptanceCounts:
    """Evaluate pytest JUnit XML against the exact frozen v0.1 step manifest."""
    try:
        # The gate only consumes JUnit XML generated by trusted Ronin CI jobs.
        root = ElementTree.parse(report_path).getroot()  # noqa: S314
    except (ElementTree.ParseError, OSError) as exc:
        raise AcceptanceGateError("v0.1 acceptance report is missing or invalid") from exc

    outcomes: dict[str, str] = {}
    unexpected = 0
    expected = set(EXPECTED_STEP_NAMES)
    for testcase in root.iter("testcase"):
        name = testcase.attrib.get("name", "")
        if not name.startswith("test_step_"):
            continue
        if name not in expected:
            unexpected += 1
            continue
        if name in outcomes:
            raise AcceptanceGateError(f"duplicate acceptance result for {name}")
        if testcase.find("failure") is not None:
            outcomes[name] = "failed"
        elif testcase.find("error") is not None:
            outcomes[name] = "errors"
        else:
            skipped = testcase.find("skipped")
            if skipped is None:
                outcomes[name] = "passed"
            elif skipped.attrib.get("type") == "pytest.xfail":
                outcomes[name] = "xfailed"
            else:
                outcomes[name] = "skipped"

    missing = len(expected - outcomes.keys())
    passed = sum(outcome == "passed" for outcome in outcomes.values())
    skipped_steps = tuple(
        name for name in EXPECTED_STEP_NAMES if outcomes.get(name) == "skipped"
    )
    xfailed = sum(outcome == "xfailed" for outcome in outcomes.values())
    failed = sum(outcome == "failed" for outcome in outcomes.values())
    errors = sum(outcome == "errors" for outcome in outcomes.values())
    live = passed + failed + errors
    return AcceptanceCounts(
        live=live,
        passed=passed,
        skipped=len(skipped_steps),
        xfailed=xfailed,
        failed=failed,
        errors=errors,
        missing=missing,
        unexpected=unexpected,
        skipped_steps=skipped_steps,
    )


def require_strict_success(counts: AcceptanceCounts) -> None:
    """Reject any non-passing, missing, renamed, skipped, or xfailed required step."""
    if not counts.is_strict_success:
        raise AcceptanceGateError("strict v0.1 acceptance qualification is incomplete")


def _parse_allowed_steps(value: str) -> tuple[str, ...]:
    if not value:
        return ()
    numbers: list[int] = []
    for raw in value.split(","):
        token = raw.strip()
        if not token.isdigit():
            raise AcceptanceGateError(f"invalid allowed step {token!r}")
        number = int(token)
        if number < 1 or number > len(EXPECTED_STEP_NAMES):
            raise AcceptanceGateError(
                f"allowed step {number:02d} is outside the frozen journey"
            )
        if number in numbers:
            raise AcceptanceGateError(f"allowed step {number:02d} is duplicated")
        numbers.append(number)
    return tuple(EXPECTED_STEP_NAMES[number - 1] for number in numbers)


def require_exact_allowed_skips(
    counts: AcceptanceCounts,
    allowed_steps: tuple[str, ...],
) -> None:
    """Allow only the exact named skip set; fail on stale allowances or new skips."""
    if any((counts.xfailed, counts.failed, counts.errors, counts.missing, counts.unexpected)):
        raise AcceptanceGateError("acceptance qualification contains non-skip failures")
    actual = set(counts.skipped_steps)
    allowed = set(allowed_steps)
    if actual != allowed:
        missing_allowance = [name for name in counts.skipped_steps if name not in allowed]
        stale_allowance = [name for name in allowed_steps if name not in actual]
        detail: list[str] = []
        if missing_allowance:
            detail.append("new skips=" + ",".join(missing_allowance))
        if stale_allowance:
            detail.append("stale allowances=" + ",".join(stale_allowance))
        raise AcceptanceGateError(
            "allowed skip set does not exactly match evidence: " + "; ".join(detail)
        )


def _format_counts(counts: AcceptanceCounts) -> str:
    return (
        "v0.1 acceptance: "
        f"live={counts.live} passed={counts.passed} skipped={counts.skipped} "
        f"xfailed={counts.xfailed} failed={counts.failed} errors={counts.errors} "
        f"missing={counts.missing} unexpected={counts.unexpected} "
        f"total={counts.total_expected} strict_success={str(counts.is_strict_success).lower()}"
    )


def _write_evidence(path: Path, counts: AcceptanceCounts) -> None:
    path.write_text(
        json.dumps(counts.to_evidence(), sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("junit_report", type=Path)
    parser.add_argument("--evidence-json", type=Path)
    parser.add_argument("--progress-only", action="store_true")
    parser.add_argument(
        "--allow-skipped",
        default=None,
        help="comma-separated frozen step numbers; must exactly match current skips",
    )
    parser.add_argument(
        "--allow-skipped-reason",
        default=None,
        help="required non-empty reason when --allow-skipped is used",
    )
    args = parser.parse_args()
    try:
        counts = evaluate_junit(args.junit_report)
        print(_format_counts(counts))
        if args.evidence_json is not None:
            _write_evidence(args.evidence_json, counts)
        if args.progress_only:
            if args.allow_skipped is not None or args.allow_skipped_reason is not None:
                raise AcceptanceGateError(
                    "--progress-only cannot be combined with skip allowances"
                )
        elif args.allow_skipped is None:
            if args.allow_skipped_reason is not None:
                raise AcceptanceGateError("--allow-skipped-reason requires --allow-skipped")
            require_strict_success(counts)
        else:
            if not args.allow_skipped_reason or not args.allow_skipped_reason.strip():
                raise AcceptanceGateError("--allow-skipped requires a non-empty reason")
            require_exact_allowed_skips(counts, _parse_allowed_steps(args.allow_skipped))
    except AcceptanceGateError as exc:
        print(f"v0.1 acceptance gate failed: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
