"""Small deterministic PySpark generator for the certified starter subset."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

from .blueprint import BlueprintContract
from .model import ScopeSelection, SourceInventory


@dataclass(frozen=True, slots=True)
class GeneratedProgram:
    path: str
    content: str
    blueprint_digest: str | None


@dataclass(frozen=True, slots=True)
class GeneratedProject:
    """A deterministic, reviewable project candidate emitted from a frozen scope."""

    files: tuple[GeneratedProgram, ...]
    manifest: str
    inventory_digest: str
    scope_digest: str
    blueprint_digest: str | None
    project_digest: str


def export_migration_script(
    project: GeneratedProject, *, filename: str = "ronin_migration.py"
) -> GeneratedProgram:
    """Build a standalone PySpark migration launcher for use outside Ronin."""
    if not filename or filename != filename.strip() or "/" in filename or "\\" in filename:
        raise ValueError("export filename must be a path-safe token")
    manifest_literal = repr(project.manifest)
    content = "\n".join(
        (
            '"""Portable migration exported from Ronin Migration Studio.',
            "",
            "The embedded manifest is provenance only; execute after reviewing and qualifying.",
            '"""',
            "from __future__ import annotations",
            "import argparse",
            "from pyspark.sql import SparkSession",
            "",
            f"MANIFEST_JSON = {manifest_literal}",
            f"PROJECT_DIGEST = {project.project_digest!r}",
            "",
            "def main() -> int:",
            "    parser = argparse.ArgumentParser("
            "description='Run a Ronin Migration Studio export')",
            "    parser.add_argument('--source', required=True, help='Input Delta path')",
            "    parser.add_argument('--output', required=True, help='Output Delta path')",
            "    parser.add_argument('--app-name', default='ronin-migration-export')",
            "    args = parser.parse_args()",
            "    spark = SparkSession.builder.appName(args.app_name).getOrCreate()",
            "    try:",
            "        source = spark.read.format('delta').load(args.source)",
            "        result = source",
            "        result.write.format('delta').mode('overwrite').save(args.output)",
            "    finally:",
            "        spark.stop()",
            "    return 0",
            "",
            "if __name__ == '__main__':",
            "    raise SystemExit(main())",
            "",
        )
    )
    return GeneratedProgram(filename, content, project.blueprint_digest)


def generate_pyspark(
    *, name: str, source_path: str, blueprint: BlueprintContract | None = None
) -> GeneratedProgram:
    """Generate a reviewable read/write skeleton; never claims semantic equivalence."""
    if not name or name != name.strip() or not source_path or source_path != source_path.strip():
        raise ValueError("generator name and source_path must be non-empty and trimmed")
    content = "\n".join(
        (
            '"""Generated by Ronin Migration Studio; qualification is required."""',
            "from pyspark.sql import SparkSession",
            "",
            "spark = SparkSession.builder.appName(" + repr(name) + ").getOrCreate()",
            'source = spark.read.format("delta").load(' + repr(source_path) + ")",
            "result = source",
            'result.write.format("delta").mode("overwrite").save("output")',
            "spark.stop()",
            "",
        )
    )
    return GeneratedProgram(f"src/{name}.py", content, blueprint.digest if blueprint else None)


def generate_project(
    *,
    inventory: SourceInventory,
    selection: ScopeSelection,
    blueprint: BlueprintContract | None = None,
) -> GeneratedProject:
    """Generate one deterministic program per selected migration unit plus a manifest.

    This is intentionally a candidate project: source semantics remain explicit in the
    manifest and every generated file carries the frozen inventory/scope provenance.
    """
    known = {unit.key: unit for unit in inventory.units}
    missing = set(selection.all_units) - set(known)
    if missing:
        raise ValueError(f"scope references unknown migration units: {sorted(missing)}")
    programs: list[GeneratedProgram] = []
    for key in selection.all_units:
        unit = known[key]
        if unit.state == "unsupported":
            raise ValueError(f"cannot generate unsupported migration unit: {key}")
        safe_name = "".join(char if char.isalnum() else "_" for char in unit.name).strip("_")
        safe_name = safe_name or "migration_unit"
        program = generate_pyspark(
            name=safe_name, source_path=f"source://{key}", blueprint=blueprint
        )
        content = program.content.replace(
            '"""Generated by Ronin Migration Studio; qualification is required."""',
            '"""Generated by Ronin Migration Studio; qualification is required."""\n'
            f"# source_unit={key}\n"
            f"# inventory_digest={inventory.digest}\n"
            f"# scope_digest={selection.digest}",
        )
        programs.append(GeneratedProgram(program.path, content, program.blueprint_digest))
    manifest_payload = {
        "schema": "ronin.migration.generated-project/v1",
        "adapter": inventory.adapter_id,
        "inventory_digest": inventory.digest,
        "scope_digest": selection.digest,
        "blueprint_digest": blueprint.digest if blueprint else None,
        "units": list(selection.all_units),
        "files": [program.path for program in programs],
        "qualification_required": True,
    }
    manifest = json.dumps(manifest_payload, sort_keys=True, separators=(",", ":"))
    project_digest = hashlib.sha256(
        (manifest + "\n" + "\n".join(program.content for program in programs)).encode()
    ).hexdigest()
    return GeneratedProject(
        tuple(programs),
        manifest,
        inventory.digest,
        selection.digest,
        blueprint.digest if blueprint else None,
        project_digest,
    )


__all__ = (
    "GeneratedProgram",
    "GeneratedProject",
    "export_migration_script",
    "generate_project",
    "generate_pyspark",
)
