const catalog={"aws.s3.bucket":["S3 bucket","storage"],"aws.lambda.function":["Lambda function","compute"],"aws.sqs.queue":["SQS queue","messaging"],"aws.dynamodb.table":["DynamoDB table","database"]};
const resources=[];const edges=[];const history=[];let historyIndex=-1;let selected=null;let linkFrom=null;let zoom=1;const palette=document.querySelector('#palette');const canvas=document.querySelector('#canvas');
const hclButton=document.createElement('button');hclButton.id='import-hcl';hclButton.textContent='Import HCL';document.querySelector('header').append(hclButton);const hclFile=document.createElement('input');hclFile.id='hcl-file';hclFile.type='file';hclFile.accept='.tf,text/plain';hclFile.hidden=true;document.body.append(hclFile);
function snapshot(){history.splice(historyIndex+1);history.push(JSON.stringify({resources,edges}));historyIndex=history.length-1}
function restore(raw){const value=JSON.parse(raw);resources.splice(0,resources.length,...value.resources);edges.splice(0,edges.length,...value.edges);render()}
function render(){document.querySelectorAll('.node').forEach(n=>n.remove());resources.forEach((resource,index)=>{const node=document.createElement('div');node.className='node';node.tabIndex=0;node.dataset.id=resource.id;node.style.left=`${resource.x??40+(index%3)*210}px`;node.style.top=`${resource.y??40+Math.floor(index/3)*100}px`;node.innerHTML=`<b>${catalog[resource.type][0]} · ${resource.name}</b><small>${resource.id}</small>`;node.onclick=event=>{event.stopPropagation();if(event.shiftKey&&linkFrom&&linkFrom!==resource.id){edges.push([linkFrom,resource.id]);snapshot();document.querySelector('#status').textContent=`Connected ${linkFrom} → ${resource.id}`}else{linkFrom=resource.id}select(resource,node)};node.onkeydown=event=>{if(event.key==='Enter')select(resource,node);if(event.key==='Delete')removeResource(resource.id)};canvas.append(node)});drawEdges();canvas.querySelector('.empty').style.display=resources.length?'none':'block'}
function drawEdges(){const svg=document.querySelector('#edges');svg.replaceChildren();for(const [source,target] of edges){const a=document.querySelector(`[data-id="${source}"]`),b=document.querySelector(`[data-id="${target}"]`);if(!a||!b)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',String(parseInt(a.style.left)+180));line.setAttribute('y1',String(parseInt(a.style.top)+30));line.setAttribute('x2',String(parseInt(b.style.left)));line.setAttribute('y2',String(parseInt(b.style.top)+30));line.setAttribute('class','edge');svg.append(line)}}
function removeResource(id){const index=resources.findIndex(item=>item.id===id);if(index>=0){resources.splice(index,1);for(let i=edges.length-1;i>=0;i--)if(edges[i].includes(id))edges.splice(i,1);snapshot();render()}}
function applyZoom(){canvas.style.setProperty('--canvas-zoom',zoom);document.querySelector('#zoom-reset').textContent=`${Math.round(zoom*100)}%`}
Object.entries(catalog).forEach(([type,[label,category]])=>{const item=document.createElement('div');item.className='palette-item';item.draggable=true;item.dataset.type=type;item.innerHTML=`${label}<small>${category}</small>`;item.ondragstart=e=>e.dataTransfer.setData('text/plain',type);palette.append(item)});
canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const type=e.dataTransfer.getData('text/plain');const id=`r${resources.length+1}`;resources.push({id,type,name:`${type.split('.').at(-1)}_${resources.length+1}`,properties:{}});snapshot();render()};
function select(resource,node){selected=resource;document.querySelectorAll('.node').forEach(item=>item.classList.remove('selected'));node.classList.add('selected');document.querySelector('#name').disabled=false;document.querySelector('#value').disabled=false;document.querySelector('#save').disabled=false;document.querySelector('#name').value=resource.name;document.querySelector('#value').value=resource.properties.value||''}
document.querySelector('#save').onclick=()=>{if(!selected)return;selected.name=document.querySelector('#name').value;selected.properties.value=document.querySelector('#value').value;snapshot();render()};
document.querySelector('#undo').onclick=()=>{if(historyIndex>0)restore(history[--historyIndex])};document.querySelector('#redo').onclick=()=>{if(historyIndex<history.length-1)restore(history[++historyIndex])};document.querySelector('#import').onclick=()=>document.querySelector('#file').click();document.querySelector('#file').onchange=async event=>{const file=event.target.files[0];if(file)restore(await file.text());snapshot()};
hclButton.onclick=()=>hclFile.click();hclFile.onchange=async event=>{const file=event.target.files[0];if(!file)return;try{const imported=await call('/v1/cloud-studio/import',{hcl:await file.text()});resources.splice(0,resources.length,...imported.resources);edges.splice(0,edges.length,...imported.edges);snapshot();render();document.querySelector('#status').textContent=`Imported ${resources.length} resources`}catch(error){document.querySelector('#status').textContent=`HCL import failed: ${error.message}`}};
document.querySelector('#export-json').onclick=()=>{const blob=new Blob([JSON.stringify({resources,edges},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='cloud-topology.json';link.click();URL.revokeObjectURL(link.href)};
document.querySelector('#zoom-in').onclick=()=>{zoom=Math.min(2,zoom+.1);applyZoom()};document.querySelector('#zoom-out').onclick=()=>{zoom=Math.max(.5,zoom-.1);applyZoom()};document.querySelector('#zoom-reset').onclick=()=>{zoom=1;applyZoom()};document.querySelector('#layout').onclick=()=>{const incoming=new Set(edges.map(edge=>edge[1]));const levels=[];resources.forEach(resource=>{let level=0;let parent=edges.find(edge=>edge[1]===resource.id);while(parent){level++;parent=edges.find(edge=>edge[1]===parent[0])}levels.push(level)});const counts={};resources.forEach((resource,index)=>{const level=levels[index];resource.x=40+level*240;resource.y=40+(counts[level]||0)*110;counts[level]=(counts[level]||0)+1});snapshot();render();document.querySelector('#status').textContent=`Auto-layout applied to ${resources.length} nodes`};
document.querySelector('#validate').onclick=async()=>{const result=await call('/v1/cloud-studio/validate',{resources,edges});document.querySelector('#status').textContent=result.valid?'Topology valid':result.errors.join('; ')};
async function call(url,payload){const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});return res.json()}
document.querySelector('#export').onclick=async()=>{try{document.querySelector('#output').textContent=(await call('/v1/cloud-studio/terraform',{resources,edges})).content}catch{document.querySelector('#output').textContent='Connect Ronin to export this topology.'}document.querySelector('#output').hidden=false};
snapshot();
